/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package neu.edu.csye6200.views;

import javax.swing.JButton;
import javax.swing.JTextField;

/**
 *
 * @author 
 */
public class PanelUpdateTeacher extends javax.swing.JPanel {

    /**
     * Creates new form UpdateTeacherJPanel
     */
    public PanelUpdateTeacher() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFirstName = new javax.swing.JLabel();
        lblLastName = new javax.swing.JLabel();
        lblClassRoomAssigned = new javax.swing.JLabel();
        lblTeacherId = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        txtClassRoomAssigned = new javax.swing.JTextField();
        txtTeacherId = new javax.swing.JTextField();
        btnUpdateTeacher = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 102, 204));

        lblFirstName.setFont(new java.awt.Font("Charter", 0, 14)); // NOI18N
        lblFirstName.setForeground(new java.awt.Color(251, 243, 228));
        lblFirstName.setText("First Name");

        lblLastName.setFont(new java.awt.Font("Charter", 0, 14)); // NOI18N
        lblLastName.setForeground(new java.awt.Color(251, 243, 228));
        lblLastName.setText("Last Name:");

        lblClassRoomAssigned.setFont(new java.awt.Font("Charter", 0, 14)); // NOI18N
        lblClassRoomAssigned.setForeground(new java.awt.Color(251, 243, 228));
        lblClassRoomAssigned.setText("Class Room Assigned:");

        lblTeacherId.setFont(new java.awt.Font("Charter", 0, 14)); // NOI18N
        lblTeacherId.setForeground(new java.awt.Color(251, 243, 228));
        lblTeacherId.setText("Teacher Id:");

        txtFirstName.setFont(new java.awt.Font("Charter", 0, 14)); // NOI18N

        txtLastName.setFont(new java.awt.Font("Charter", 0, 14)); // NOI18N

        txtClassRoomAssigned.setEditable(false);
        txtClassRoomAssigned.setFont(new java.awt.Font("Charter", 0, 14)); // NOI18N

        txtTeacherId.setEditable(false);
        txtTeacherId.setFont(new java.awt.Font("Charter", 0, 14)); // NOI18N
        txtTeacherId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTeacherIdActionPerformed(evt);
            }
        });

        btnUpdateTeacher.setFont(new java.awt.Font("Charter", 1, 14)); // NOI18N
        btnUpdateTeacher.setForeground(new java.awt.Color(204, 0, 0));
        btnUpdateTeacher.setText("Update");

        lblTitle.setFont(new java.awt.Font("Charter", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(251, 243, 228));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("UPDATE TEACHER");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblLastName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblClassRoomAssigned, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTeacherId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtFirstName)
                            .addComponent(txtLastName, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                            .addComponent(txtClassRoomAssigned)
                            .addComponent(txtTeacherId)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addComponent(btnUpdateTeacher)))
                .addContainerGap(162, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblClassRoomAssigned, lblFirstName, lblLastName, lblTeacherId});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtClassRoomAssigned, txtFirstName, txtLastName, txtTeacherId});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFirstName)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLastName)
                    .addComponent(txtLastName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblClassRoomAssigned, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtClassRoomAssigned, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTeacherId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTeacherId))
                .addGap(20, 20, 20)
                .addComponent(btnUpdateTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(223, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblClassRoomAssigned, lblFirstName, lblLastName, lblTeacherId, txtClassRoomAssigned, txtFirstName, txtLastName, txtTeacherId});

    }// </editor-fold>//GEN-END:initComponents

    private void txtTeacherIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTeacherIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTeacherIdActionPerformed

    public JButton getBtnUpdate() {
        return btnUpdateTeacher;
    }

    public void setBtnUpdate(JButton btnUpdate) {
        this.btnUpdateTeacher = btnUpdate;
    }

    public JTextField getTextFieldClassRoomAssigned() {
        return txtClassRoomAssigned;
    }

    public void setTextFieldClassRoomAssigned(JTextField textFieldClassRoomAssigned) {
        this.txtClassRoomAssigned = textFieldClassRoomAssigned;
    }

    public JTextField getTextFieldTeacherId() {
        return txtTeacherId;
    }

    public void setTextFieldTeacherId(JTextField textFieldTeacherId) {
        this.txtTeacherId = textFieldTeacherId;
    }

    public JTextField getTxtFieldFName() {
        return txtFirstName;
    }

    public void setTxtFieldFName(JTextField txtFieldFName) {
        this.txtFirstName = txtFieldFName;
    }

    public JTextField getTxtFieldLName() {
        return txtLastName;
    }

    public void setTxtFieldLName(JTextField txtFieldLName) {
        this.txtLastName = txtFieldLName;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUpdateTeacher;
    private javax.swing.JLabel lblClassRoomAssigned;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblTeacherId;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtClassRoomAssigned;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtTeacherId;
    // End of variables declaration//GEN-END:variables
}
