/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package neu.edu.csye6200.views;

import javax.swing.JButton;
import javax.swing.JRadioButton;
import javax.swing.JTextField;

/**
 *
 * @author 
 */
public class PanelAddImmnunization extends javax.swing.JPanel {

    /**
     * Creates new form AddImmnunizationJPanel
     */
    public PanelAddImmnunization() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblImmunName = new javax.swing.JLabel();
        txtImmunName = new javax.swing.JTextField();
        lblImmunDate = new javax.swing.JLabel();
        txtImmunDate = new javax.swing.JTextField();
        lblIsImmunTaken = new javax.swing.JLabel();
        radioBtnYes = new javax.swing.JRadioButton();
        raadioBtnNo = new javax.swing.JRadioButton();
        btnAddImmunization = new javax.swing.JButton();
        lblDuration = new javax.swing.JLabel();
        txtDuration = new javax.swing.JTextField();
        lblTitle = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 153, 255));

        lblImmunName.setFont(new java.awt.Font("Charter", 0, 14)); // NOI18N
        lblImmunName.setForeground(new java.awt.Color(251, 243, 228));
        lblImmunName.setText("Immunization Name:");

        lblImmunDate.setFont(new java.awt.Font("Charter", 0, 14)); // NOI18N
        lblImmunDate.setForeground(new java.awt.Color(251, 243, 228));
        lblImmunDate.setText("Immunization Date:");

        lblIsImmunTaken.setFont(new java.awt.Font("Charter", 0, 14)); // NOI18N
        lblIsImmunTaken.setForeground(new java.awt.Color(251, 243, 228));
        lblIsImmunTaken.setText("Is Immunization Taken:");

        radioBtnYes.setFont(new java.awt.Font("Charter", 0, 14)); // NOI18N
        radioBtnYes.setForeground(new java.awt.Color(251, 243, 228));
        radioBtnYes.setText("Yes");
        radioBtnYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBtnYesActionPerformed(evt);
            }
        });

        raadioBtnNo.setFont(new java.awt.Font("Charter", 0, 14)); // NOI18N
        raadioBtnNo.setForeground(new java.awt.Color(251, 243, 228));
        raadioBtnNo.setText("No");
        raadioBtnNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                raadioBtnNoActionPerformed(evt);
            }
        });

        btnAddImmunization.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAddImmunization.setForeground(new java.awt.Color(204, 0, 0));
        btnAddImmunization.setText("Add Immunization");
        btnAddImmunization.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddImmunizationActionPerformed(evt);
            }
        });

        lblDuration.setFont(new java.awt.Font("Charter", 0, 14)); // NOI18N
        lblDuration.setForeground(new java.awt.Color(251, 243, 228));
        lblDuration.setText("Duration:");

        txtDuration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDurationActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Charter", 1, 18)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(251, 243, 228));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("ADD NEW IMMUNIZATION");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblIsImmunTaken)
                                .addComponent(lblDuration, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(raadioBtnNo)
                                .addComponent(radioBtnYes)
                                .addComponent(txtImmunDate, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtImmunName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtDuration, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(lblImmunName, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblImmunDate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnAddImmunization))
                .addContainerGap(111, Short.MAX_VALUE))
            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblDuration, lblImmunDate, lblImmunName, lblIsImmunTaken});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {raadioBtnNo, radioBtnYes, txtDuration, txtImmunDate, txtImmunName});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblImmunName, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtImmunName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtImmunDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radioBtnYes))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblImmunDate, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(lblIsImmunTaken)))
                .addGap(2, 2, 2)
                .addComponent(raadioBtnNo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDuration)
                    .addComponent(txtDuration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAddImmunization)
                .addContainerGap(176, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblDuration, lblImmunDate, lblImmunName, lblIsImmunTaken});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {raadioBtnNo, radioBtnYes, txtDuration, txtImmunDate, txtImmunName});

    }// </editor-fold>//GEN-END:initComponents

    private void btnAddImmunizationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddImmunizationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddImmunizationActionPerformed

    private void radioBtnYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBtnYesActionPerformed
        raadioBtnNo.setSelected(false);
    }//GEN-LAST:event_radioBtnYesActionPerformed

    private void raadioBtnNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_raadioBtnNoActionPerformed
        // TODO add your handling code here:
        radioBtnYes.setSelected(false);
    }//GEN-LAST:event_raadioBtnNoActionPerformed

    private void txtDurationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDurationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDurationActionPerformed

    public JTextField getTextFieldDuration() {
        return txtDuration;
    }

    public void setTextFieldDuration(JTextField textFieldDuration) {
        this.txtDuration = textFieldDuration;
    }

    public JButton getBtnAddImmunization() {
        return btnAddImmunization;
    }

    public void setBtnAddImmunization(JButton btnAddImmunization) {
        this.btnAddImmunization = btnAddImmunization;
    }

    public JRadioButton getRaadioBtnNo() {
        return raadioBtnNo;
    }

    public void setRaadioBtnNo(JRadioButton raadioBtnNo) {
        this.raadioBtnNo = raadioBtnNo;
    }

    public JRadioButton getRadioBtnYes() {
        return radioBtnYes;
    }

    public void setRadioBtnYes(JRadioButton radioBtnYes) {
        this.radioBtnYes = radioBtnYes;
    }

    public JTextField getTextFieldDate() {
        return txtImmunDate;
    }

    public void setTextFieldDate(JTextField textFieldDate) {
        this.txtImmunDate = textFieldDate;
    }

    public JTextField getTextFieldName() {
        return txtImmunName;
    }

    public void setTextFieldName(JTextField textFieldName) {
        this.txtImmunName = textFieldName;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddImmunization;
    private javax.swing.JLabel lblDuration;
    private javax.swing.JLabel lblImmunDate;
    private javax.swing.JLabel lblImmunName;
    private javax.swing.JLabel lblIsImmunTaken;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JRadioButton raadioBtnNo;
    private javax.swing.JRadioButton radioBtnYes;
    private javax.swing.JTextField txtDuration;
    private javax.swing.JTextField txtImmunDate;
    private javax.swing.JTextField txtImmunName;
    // End of variables declaration//GEN-END:variables
}
